import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface CommercialInvoiceData {
  invoiceNumber: string;
  invoiceDate: string;
  exporterName: string;
  exporterAddress: string;
  exporterGst: string;
  exporterIec: string;
  consigneeName: string;
  consigneeAddress: string;
  destinationCountry: string;
  portOfLoading: string;
  portOfDischarge: string;
  productName: string;
  hsCode: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  totalValue: number;
  currency: string;
  paymentTerms: string;
}

export function generateCommercialInvoicePDF(data: CommercialInvoiceData): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(24, 24, 27); // Charcoal
  doc.text('COMMERCIAL INVOICE (DRAFT)', 14, 20);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('EXPORT LOGISTICS READINESS PLATFORM - PROTOTYPE DRAFT', 14, 26);
  doc.text('This document is generated for export readiness verification and customs simulation.', 14, 30);

  // Line divider
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 34, 196, 34);

  // Invoice Details Grid
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);

  // Left Column (Exporter)
  doc.setFont('helvetica', 'bold');
  doc.text('EXPORTER / SHIPPER:', 14, 42);
  doc.setFont('helvetica', 'normal');
  doc.text(data.exporterName, 14, 48);
  doc.text(data.exporterAddress, 14, 53);
  doc.text(`GSTIN: ${data.exporterGst} | IEC: ${data.exporterIec}`, 14, 58);

  // Right Column (Consignee)
  doc.setFont('helvetica', 'bold');
  doc.text('CONSIGNEE / BUYER:', 110, 42);
  doc.setFont('helvetica', 'normal');
  doc.text(data.consigneeName, 110, 48);
  doc.text(data.consigneeAddress, 110, 53);
  doc.text(`Destination: ${data.destinationCountry}`, 110, 58);

  // Document Metadata Table
  doc.line(14, 64, 196, 64);

  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice No: ${data.invoiceNumber}`, 14, 72);
  doc.text(`Invoice Date: ${data.invoiceDate}`, 80, 72);
  doc.text(`Payment Terms: ${data.paymentTerms}`, 140, 72);

  doc.text(`Port of Loading: ${data.portOfLoading}`, 14, 78);
  doc.text(`Port of Discharge: ${data.portOfDischarge}`, 110, 78);

  // Product Line Items Table
  autoTable(doc, {
    startY: 85,
    head: [['Item Description', 'HS Code', 'Quantity', 'Unit Price', `Total (${data.currency})`]],
    body: [
      [
        data.productName,
        data.hsCode,
        `${data.quantity} ${data.unit}`,
        `₹${data.unitPrice.toLocaleString('en-IN')}`,
        `₹${data.totalValue.toLocaleString('en-IN')}`,
      ],
    ],
    headStyles: {
      fillColor: [249, 87, 56], // Vivid Orange
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    styles: { fontSize: 9 },
  });

  // Total Summary
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`GRAND TOTAL VALUE: ₹${data.totalValue.toLocaleString('en-IN')} ${data.currency}`, 110, finalY);

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by VyaparFlow Export Readiness System. Verified for simulated customs clearance.', 14, 280);

  return Buffer.from(doc.output('arraybuffer'));
}

export function generatePackingListPDF(data: CommercialInvoiceData & { weight: number; packages: number }): Buffer {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.setTextColor(24, 24, 27);
  doc.text('EXPORT PACKING LIST (DRAFT)', 14, 20);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('EXPORT LOGISTICS READINESS PLATFORM - SHIPMENT MANIFEST', 14, 26);

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 32, 196, 32);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Shipper: ${data.exporterName}`, 14, 40);
  doc.text(`Consignee: ${data.consigneeName}`, 110, 40);
  doc.text(`Invoice Ref: ${data.invoiceNumber}`, 14, 46);
  doc.text(`Destination: ${data.destinationCountry}`, 110, 46);

  autoTable(doc, {
    startY: 54,
    head: [['Package No / Mark', 'Contents Description', 'HS Code', 'Packages', 'Net Weight (KG)', 'Gross Weight (KG)']],
    body: [
      [
        'MARK 001-500 / VYAPARFLOW',
        data.productName,
        data.hsCode,
        `${data.packages} Drums`,
        `${data.weight.toLocaleString()} KG`,
        `${(data.weight * 1.05).toLocaleString()} KG`,
      ],
    ],
    headStyles: {
      fillColor: [24, 24, 27],
      textColor: [255, 255, 255],
    },
    styles: { fontSize: 9 },
  });

  return Buffer.from(doc.output('arraybuffer'));
}
